<a href="https://colab.research.google.com/github/shirin6767saleh/code-/blob/Fnew/new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Rationale for Sinusoids Supporting the Spectral Framework of Fractional DFTs
Let $\mathbf{G}_{\theta \in \mathbb{Z}}$ be the family  extends the classical harmonic analysis framework of the DFT by introducing a tunable parameter $\theta$

$\begin{equation}
\mathbf{G}_\theta = \left[ w^{\left(k - \frac{\theta}{2}\right)\left(\ell - \frac{\theta}{2}\right)} \right]_{k,\ell=0}^{N-1},
\end{equation}$
$\theta\in\{0,1,\cdots,2N-1\},w = e^{-j \frac{2\pi}{N}}$

$\begin{align*}
\mathbf{G}_\theta^2 &=
\begin{cases}
\mathbf{J}_{\theta + 1} \oplus  (-1)^\theta \mathbf{J}_{N - \theta - 1}  & \text{for } 0 \leq \theta < N, \\[6pt]
 (-1)^\theta \, \mathbf{J}_{\theta - N+ 1} \oplus \mathbf{J}_{2N - \theta - 1}, & \text{for } N \leq \theta < 2N,
\end{cases}\\
\mathbf{G}_\theta^4 &= I,
\end{align*}$

where:

-  $J$ is the antidiagonal matrix,



In [ ]:
import numpy as np
#parameter
N = 7
theta = 4
# Construct matrix G_theta with normalization 1/sqrt(N)
def G_theta(N, theta):
    w = np.exp(-1j * 2 * np.pi / N)
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1/np.sqrt(N)) * (w ** ((k - theta/2) * (l - theta/2)))

# Construct J_n (matrix with ones on the anti-diagonal)
def J(n):
    J = np.zeros((n, n), dtype=complex)
    for i in range(n):
        J[i, n - 1 - i] = 1
    return J

# Compute G_theta^2 according to the theoretical formula
def G_theta_squared(N, theta):
    if 0 <= theta < N:
        A = J(theta+1)
        B = (-1)**theta * J(N - theta - 1)
    elif N <= theta < 2*N:
        A = (-1)**theta * J(theta - N + 1)
        B = J(2*N - theta - 1)
    else:
        raise ValueError("theta must be between 0 and 2N-1")
    # Block diagonal (direct sum)
    return np.block([
        [A, np.zeros((A.shape[0], B.shape[1]), dtype=complex)],
        [np.zeros((B.shape[0], A.shape[1]), dtype=complex), B]
    ])

if __name__ == "__main__":


    G = G_theta(N, theta)
    G2_direct = G @ G  # matrix multiplication using @
    G2_theory = G_theta_squared(N, theta)

    print("G_theta:")
    print(np.round(G, 3))

    print("\nG_theta^2 (direct multiplication):")
    print(np.round(G2_direct, 3))

    print("\nG_theta^2 (theoretical formula):")
    print(np.round(G2_theory, 3))

    # Test correctness: compare the two results
    error = np.max(np.abs(G2_direct - G2_theory))
    print("\nMax absolute difference between direct and theoretical results:", error)
    if error < 1e-10:
        print("Test PASSED ✅")
    else:
        print("Test FAILED ❌")


G_theta:
[[-0.341+0.164j -0.084-0.368j  0.378+0.j    -0.084+0.368j -0.341-0.164j
   0.236-0.296j  0.236+0.296j]
 [-0.084-0.368j  0.236-0.296j  0.378+0.j     0.236+0.296j -0.084+0.368j
  -0.341+0.164j -0.341-0.164j]
 [ 0.378+0.j     0.378+0.j     0.378+0.j     0.378+0.j     0.378+0.j
   0.378+0.j     0.378+0.j   ]
 [-0.084+0.368j  0.236+0.296j  0.378+0.j     0.236-0.296j -0.084-0.368j
  -0.341-0.164j -0.341+0.164j]
 [-0.341-0.164j -0.084+0.368j  0.378+0.j    -0.084-0.368j -0.341+0.164j
   0.236+0.296j  0.236-0.296j]
 [ 0.236-0.296j -0.341+0.164j  0.378+0.j    -0.341-0.164j  0.236+0.296j
  -0.084-0.368j -0.084+0.368j]
 [ 0.236+0.296j -0.341-0.164j  0.378+0.j    -0.341+0.164j  0.236-0.296j
  -0.084+0.368j -0.084-0.368j]]

G_theta^2 (direct multiplication):
[[ 0.-0.j -0.+0.j -0.-0.j  0.+0.j  1.+0.j  0.-0.j  0.+0.j]
 [-0.+0.j -0.-0.j  0.+0.j  1.+0.j -0.-0.j  0.+0.j -0.-0.j]
 [-0.-0.j  0.+0.j  1.+0.j  0.-0.j  0.+0.j -0.+0.j  0.-0.j]
 [ 0.+0.j  1.+0.j  0.-0.j  0.+0.j -0.+0.j  0.-0.j  0.+0.j]


#Let the parameterized discrete trigonometric transforms be defined as follows:
$\begin{equation}
\mathrm{DCT}_\theta = \frac{1}{\sqrt{N}}
\left[ \cos\!\left((k - \tfrac{\theta}{2})(l - \tfrac{\theta}{2}) \tfrac{2\pi}{N}\right) \right]_{k,l=0}^{N-1},\quad\mathrm{DST}_\theta = \frac{1}{\sqrt{N}}
\left[ \sin\!\left((k - \tfrac{\theta}{2})(l - \tfrac{\theta}{2}) \tfrac{2\pi}{N}\right) \right]_{k,l=0}^{N-1}.
\end{equation}$

Where

\begin{equation}
\begin{cases}
\mathbf{G}_\theta = \left(\mathrm{DCT}_\theta + i\,\mathrm{DST}_\theta \right), \\[4pt]   
\mathrm{DCT}_\theta \cdot \mathrm{DST}_\theta = \mathbf{0},
\end{cases}
\end{equation}

-  Table 2
-  eigenvalues of DCT and DST
-  \begin{equation}
\begin{cases}
\mathrm{DCT}_\theta = \mathbf{G}_\theta^3 + \mathbf{G}_\theta, \\[4pt]   
i\,\mathrm{DST}_\theta = \mathbf{G}_\theta^3 - \mathbf{G}_\theta,
\end{cases}
\end{equation}

-  \begin{equation}
\begin{cases}
\dfrac{1}{2}\,\mathrm{DCT}_\theta^2 = \mathbf{G}_\theta^2 + \mathbf{I},\\  
\dfrac{1}{2}\,\mathrm{DST}_\theta^2 = \mathbf{G}_\theta^2 - \mathbf{I}.
\end{cases}
\end{equation}

In [ ]:
import numpy as np

# Construct DCT_theta
def DCT_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1/np.sqrt(N)) * np.cos(((k - theta/2) * (l - theta/2)) * 2*np.pi/N)

# Construct DST_theta
def DST_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1/np.sqrt(N)) * np.sin(((k - theta/2) * (l - theta/2)) * 2*np.pi/N)

# Construct G_theta from DCT and DST
def G_theta(N, theta):
    DCT = DCT_theta(N, theta)
    DST = DST_theta(N, theta)
    return  (DCT + 1j * DST)

# Function to print check result with green tick or red cross
def print_check(name, result):
    symbol = '\u2705' if result else '\u274C'
    print(f"{name} passed? {symbol}")

# Example usage
if __name__ == "__main__":
    N = 6
    theta = 3

    # Compute DCT and DST
    DCT = DCT_theta(N, theta)
    DST = DST_theta(N, theta)

    # 1) Check if DCT @ DST is approximately zero
    check1 = DCT @ DST
    print("DCT @ DST (should be close to zero):")
    print(np.round(check1, 10))
    print_check("Check 1", np.allclose(check1, 0, atol=1e-10))

    # 2) Check G_theta =(DCT + i*DST)
    G = G_theta(N, theta)
    G_check = (DCT + 1j * DST)
    print_check("Check 2", np.allclose(G, G_check, atol=1e-10))

    # 3) Check G_theta @ P_1 - P_1 ~ 0
    P_1 = 0.25 * ((DCT @ DCT) + DCT)
    check3 = G @ P_1 - P_1
    print_check("Check 3", np.allclose(check3, 0, atol=1e-10))

    # 4) Check G_theta @ P_minus1 + P_minus1 ~ 0
    P_minus1 = 0.25 * ((DCT @ DCT) - DCT)
    check4 = G @ P_minus1 + P_minus1
    print_check("Check 4", np.allclose(check4, 0, atol=1e-10))

# 5) Check G_theta @ 0.25*((DST@DST)-DST) + i*0.25*(0.5*(DST@DST)-DST) ~ 0
    P_minusi = 0.25 * ((DST @ DST) - DST)
    check5 = G @ P_minusi + 1j * P_minusi
    print_check("Check 5", np.allclose(check5, 0, atol=1e-10))

    # 6) Check G_theta @ 0.25*((DST@DST)+DST) - i*0.25*(0.5*(DST@DST)+DST) ~ 0
    P_plusi = 0.25 * ((DST @ DST) + DST)
    check6 = G @ P_plusi - 1j * P_plusi
    print_check("Check 6", np.allclose(check6, 0, atol=1e-10))
    # 7) Eigenvalue spectrum of DCT
    eigvals_DCT = np.unique(np.round(np.linalg.eigvals(DCT).real, decimals=5))
    print("\nEigenvalues of DCT:")
    print(eigvals_DCT)
    print("*" * 40)
    # 7) Eigenvalue spectrum of DST
    eigvals_DST = np.unique(np.round(np.linalg.eigvals(DST).real, decimals=5))
    print("\nEigenvalues of DST:")
    print(eigvals_DST)
    print("*" * 40)
    # 8) Check DCT_theta = 0.5*(G_theta^3 + G_theta)
    check_DCT_relation = np.allclose(DCT,0.5*(G @ G @ G + G), atol=1e-10)
    print_check("Check 8: DCT_theta = G_theta^3 + G_theta", check_DCT_relation)
    # 9) Check i*DST_theta =0.5*(G_theta^3 - G_theta)
    check_DST_relation = np.allclose(1j*DST, 0.5*(G -G @ G @ G), atol=1e-10)
    print_check("Check 9: i*DST_theta =0.5*( G_theta - G_theta^3)", check_DST_relation)
    # 10) Check DCT^2 = 0.5*(G^2 + I)
    I = np.eye(N)
    check_DCT2_relation = np.allclose((DCT @ DCT), 0.5*(G @ G + I), atol=1e-10)
    print_check("Check 10: 0.5*DCT^2 =0.5*(G^2 + I)", check_DCT2_relation)
    # 11) Check DST^2 = 0.5*(G^2 - I)
    check_DST2_relation = np.allclose((DST @ DST),0.5*(I- G @ G), atol=1e-10)
    print_check("Check 11: DST^2 = 0.5*(i - G^2)", check_DST2_relation)



DCT @ DST (should be close to zero):
[[-0.  0. -0.  0. -0. -0.]
 [-0. -0.  0.  0.  0.  0.]
 [-0. -0.  0.  0.  0.  0.]
 [-0.  0. -0.  0. -0. -0.]
 [-0.  0. -0.  0.  0.  0.]
 [ 0. -0.  0. -0. -0. -0.]]
Check 1 passed? ✅
Check 2 passed? ✅
Check 3 passed? ✅
Check 4 passed? ✅
Check 5 passed? ✅
Check 6 passed? ✅

Eigenvalues of DCT:
[-1.  0.  1.]
****************************************

Eigenvalues of DST:
[-1. -0.  1.]
****************************************
Check 8: DCT_theta = G_theta^3 + G_theta passed? ✅
Check 9: i*DST_theta =0.5*( G_theta - G_theta^3) passed? ✅
Check 10: 0.5*DCT^2 =0.5*(G^2 + I) passed? ✅
Check 11: DST^2 = 0.5*(i - G^2) passed? ✅


-  Let $\theta=0$, then  $G_\theta=F$
- $\theta=N-1$ then  $G_\theta=G_c$
- $\theta=2N-1$ then  $G_\theta=G$

table3
-  $\theta=0$ and $N=4m$

In [ ]:
import numpy as np

m = 2
N = 4 * m
theta = 0

# Construct DCT_theta
def DCT_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1 / np.sqrt(N)) * np.cos(((k - theta / 2) * (l - theta / 2)) * 2 * np.pi / N)

# Construct DST_theta
def DST_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1 / np.sqrt(N)) * np.sin(((k - theta / 2) * (l - theta / 2)) * 2 * np.pi / N)

DCT = DCT_theta(N, theta)
DST = DST_theta(N, theta)

P_1 = 0.25 * ((DCT @ DCT) + DCT)
P_minus1 = 0.25 * ((DCT @ DCT) - DCT)
P_plusi = 0.25 * ((DST @ DST) + DST)
P_minusi = 0.25 * ((DST @ DST) - DST)

# Adjusting part1 and part2 to have the same number of rows
part1 = P_1[m-1:2*m, 0:m]  # Shape (3, 2)
part2 = P_1[m-1:2*m, 2*m][:, np.newaxis]  # Shape (3, 1)

Part11 = P_minusi[m:2*m, 1:m]
Part12 = P_minusi[m:2*m, 2*m-1][:, np.newaxis]

#-----block selected B(0 ,lambda)--------#----
B1 = np.hstack([part1, part2])  # Now both parts have 3 rows
Bminus1 = P_minus1[m:2*m, 0:m]
Bplusi = P_plusi[m+1:2*m, 1:m]
Bminusi = np.hstack([Part11, Part12])  # Corrected variable names

# Determinants--------------------
detB1 = np.linalg.det(B1)
detBminus1 = np.linalg.det(Bminus1)
detBplusi = np.linalg.det(Bplusi)
detBminusi = np.linalg.det(Bminusi)

# Output results
print("Determinant of B1:", detB1)
if np.isclose(detB1, 0):
    print("Matrix B1 is NOT invertible")
else:
    print("Matrix B1 is invertible")

print("Determinant of Bminus1:", detBminus1)
if np.isclose(detBminus1, 0):
    print("Matrix Bminus1 is NOT invertible")
else:
    print("Matrix Bminus1 is invertible")

print("Determinant of Bplusi:", detBplusi)
if np.isclose(detBplusi, 0):
    print("Matrix Bplusi is NOT invertible")
else:
    print("Matrix Bplusi is invertible")

print("Determinant of Bminusi:", detBminusi)
if np.isclose(detBminusi, 0):
    print("Matrix Bminusi is NOT invertible")
else:
    print("Matrix Bminusi is invertible")


Determinant of B1: 0.0039062499999999974
Matrix B1 is invertible
Determinant of Bminus1: -0.005524271728019904
Matrix Bminus1 is invertible
Determinant of Bplusi: 0.06250000000000003
Matrix Bplusi is invertible
Determinant of Bminusi: -8.586443133426875e-18
Matrix Bminusi is NOT invertible


-  $\theta=0$ and $N=4m+1$

In [ ]:
import numpy as np

m = 2
N = 4 * m+1
theta = 0

# Construct DCT_theta
def DCT_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1 / np.sqrt(N)) * np.cos(((k - theta / 2) * (l - theta / 2)) * 2 * np.pi / N)

# Construct DST_theta
def DST_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1 / np.sqrt(N)) * np.sin(((k - theta / 2) * (l - theta / 2)) * 2 * np.pi / N)

DCT = DCT_theta(N, theta)
DST = DST_theta(N, theta)

P_1 = 0.25 * ((DCT @ DCT) + DCT)
P_minus1 = 0.25 * ((DCT @ DCT) - DCT)
P_plusi = 0.25 * ((DST @ DST) + DST)
P_minusi = 0.25 * ((DST @ DST) - DST)
# Adjusting part1 and part2 to have the same number of rows
part1 = P_1[m:2*m+1,0:m]
part2 = P_1[m:2*m+1, 2*m][:, np.newaxis]

#-----block selected B(0 ,lambda)--------#----
B1 = np.hstack([part1, part2])
Bminus1 = P_minus1[m+1:2*m+1, 0:m]
Bplusi = P_plusi[m+1:2*m+1,1:m+1]
Bminusi = P_minusi[m+1:2*m+1,1:m+1]
# Determinants--------------------
detB1 = np.linalg.det(B1)
detBminus1 = np.linalg.det(Bminus1)
detBplusi = np.linalg.det(Bplusi)
detBminusi = np.linalg.det(Bminusi)

# Output results
print("Determinant of B1:", detB1)
if np.isclose(detB1, 0):
    print("Matrix B1 is NOT invertible")
else:
    print("Matrix B1 is invertible")

print("Determinant of Bminus1:", detBminus1)
if np.isclose(detBminus1, 0):
    print("Matrix Bminus1 is NOT invertible")
else:
    print("Matrix Bminus1 is invertible")
print("Determinant of Bplusi:", detBplusi)
if np.isclose(detBplusi, 0):
    print("Matrix Bplusi is NOT invertible")
else:
    print("Matrix Bplusi is invertible")
print("Determinant of Bminusi:", detBminusi)
if np.isclose(detBminusi, 0):
    print("Matrix Bminusi is NOT invertible")
else:
    print("Matrix Bminusi is invertible")

Determinant of B1: -0.0011695280862273083
Matrix B1 is invertible
Determinant of Bminus1: -0.0030534209776799264
Matrix Bminus1 is invertible
Determinant of Bplusi: -0.0018088351840305282
Matrix Bplusi is invertible
Determinant of Bminusi: -0.001808835184030525
Matrix Bminusi is invertible


-  $\theta=0$ and $N=4m+2$

In [ ]:
import numpy as np

m = 2
N = 4 * m + 2
theta = 0

# Construct DCT_theta
def DCT_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1 / np.sqrt(N)) * np.cos(((k - theta / 2) * (l - theta / 2)) * 2 * np.pi / N)

# Construct DST_theta
def DST_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1 / np.sqrt(N)) * np.sin(((k - theta / 2) * (l - theta / 2)) * 2 * np.pi / N)

DCT = DCT_theta(N, theta)
DST = DST_theta(N, theta)

P_1 = 0.25 * ((DCT @ DCT) + DCT)
P_minus1 = 0.25 * ((DCT @ DCT) - DCT)
P_plusi = 0.25 * ((DST @ DST) + DST)
P_minusi = 0.25 * ((DST @ DST) - DST)
# Adjusting part1 and part2 to have the same number of rows


#-----block selected B(0 ,lambda)--------#----
B1 = P_1[m:2*m+1,0:m+1]
Bminus1 = P_minus1[m:2*m+1, 0:m+1]
Bplusi = P_plusi[m+1:2*m+1,1:m+1]
Bminusi = P_minusi[m+1:2*m+1,1:m+1]
# Determinants--------------------
detB1 = np.linalg.det(B1)
detBminus1 = np.linalg.det(Bminus1)
detBplusi = np.linalg.det(Bplusi)
detBminusi = np.linalg.det(Bminusi)

# Output results
print("Determinant of B1:", detB1)
if np.isclose(detB1, 0):
    print("Matrix B1 is NOT invertible")
else:
    print("Matrix B1 is invertible")

print("Determinant of Bminus1:", detBminus1)
if np.isclose(detBminus1, 0):
    print("Matrix Bminus1 is NOT invertible")
else:
    print("Matrix Bminus1 is invertible")
print("Determinant of Bplusi:", detBplusi)
if np.isclose(detBplusi, 0):
    print("Matrix Bplusi is NOT invertible")
else:
    print("Matrix Bplusi is invertible")
print("Determinant of Bminusi:", detBminusi)
if np.isclose(detBminusi, 0):
    print("Matrix Bminusi is NOT invertible")
else:
    print("Matrix Bminusi is invertible")

Determinant of B1: -0.0007320437691006419
Matrix B1 is invertible
Determinant of Bminus1: -4.920623089935832e-05
Matrix Bminus1 is invertible
Determinant of Bplusi: -0.0034938562148434204
Matrix Bplusi is invertible
Determinant of Bminusi: -0.0034938562148434204
Matrix Bminusi is invertible


-  $\theta=0$ and $N=4m+3$

In [ ]:
import numpy as np

m = 2
N = 4 * m + 3
theta = 0

# Construct DCT_theta
def DCT_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1 / np.sqrt(N)) * np.cos(((k - theta / 2) * (l - theta / 2)) * 2 * np.pi / N)

# Construct DST_theta
def DST_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1 / np.sqrt(N)) * np.sin(((k - theta / 2) * (l - theta / 2)) * 2 * np.pi / N)

DCT = DCT_theta(N, theta)
DST = DST_theta(N, theta)

P_1 = 0.25 * ((DCT @ DCT) + DCT)
P_minus1 = 0.25 * ((DCT @ DCT) - DCT)
P_plusi = 0.25 * ((DST @ DST) + DST)
P_minusi = 0.25 * ((DST @ DST) - DST)
# Adjusting part1 and part2 to have the same number of rows
part1= P_minusi[m+1:2*m+2,1:m+1]
part2 = P_minusi[m+1:2*m+2,2*m+1][:, np.newaxis]

#-----block selected B(0 ,lambda)--------#----
B1 = P_1[m+1:2*m+2,0:m+1]
Bminus1 = P_minus1[m+1:2*m+2, 0:m+1]
Bplusi = P_plusi[m+2:2*m+2,1:m+1]
Bminusi = np.hstack([part1, part2])
# Determinants--------------------
detB1 = np.linalg.det(B1)
detBminus1 = np.linalg.det(Bminus1)
detBplusi = np.linalg.det(Bplusi)
detBminusi = np.linalg.det(Bminusi)

# Output results
print("Determinant of B1:", detB1)
if np.isclose(detB1, 0):
    print("Matrix B1 is NOT invertible")
else:
    print("Matrix B1 is invertible")

print("Determinant of Bminus1:", detBminus1)
if np.isclose(detBminus1, 0):
    print("Matrix Bminus1 is NOT invertible")
else:
    print("Matrix Bminus1 is invertible")
print("Determinant of Bplusi:", detBplusi)
if np.isclose(detBplusi, 0):
    print("Matrix Bplusi is NOT invertible")
else:
    print("Matrix Bplusi is invertible")
print("Determinant of Bminusi:", detBminusi)
if np.isclose(detBminusi, 0):
    print("Matrix Bminusi is NOT invertible")
else:
    print("Matrix Bminusi is invertible")

Determinant of B1: -0.00010929149218768358
Matrix B1 is invertible
Determinant of Bminus1: 0.0001092914921876859
Matrix Bminus1 is invertible
Determinant of Bplusi: -0.0007370689888239717
Matrix Bplusi is invertible
Determinant of Bminusi: 7.558143139254461e-19
Matrix Bminusi is NOT invertible


- $\theta=N-1$ and $N=4m$

In [9]:
import numpy as np

m = 2
N = 4 * m
theta = N-1

# Construct DCT_theta
def DCT_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1 / np.sqrt(N)) * np.cos(((k - theta / 2) * (l - theta / 2)) * 2 * np.pi / N)

# Construct DST_theta
def DST_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1 / np.sqrt(N)) * np.sin(((k - theta / 2) * (l - theta / 2)) * 2 * np.pi / N)

DCT = DCT_theta(N, theta)
DST = DST_theta(N, theta)

P_1 = 0.25 * ((DCT @ DCT) + DCT)
P_minus1 = 0.25 * ((DCT @ DCT) - DCT)
P_plusi = 0.25 * ((DST @ DST) + DST)
P_minusi = 0.25 * ((DST @ DST) - DST)


#-----block selected B(0 ,lambda)--------#----
B1 = P_1[0:m,m:2*m]
Bminus1 = P_minus1[0:m, m:2*m]
Bplusi = P_plusi[0:m,m:2*m]
Bminusi = P_minusi[0:m,m:2*m]
# Determinants--------------------
detB1 = np.linalg.det(B1)
detBminus1 = np.linalg.det(Bminus1)
detBplusi = np.linalg.det(Bplusi)
detBminusi = np.linalg.det(Bminusi)

# Output results
print("Determinant of B1:", detB1)
if np.isclose(detB1, 0):
    print("Matrix B1 is NOT invertible")
else:
    print("Matrix B1 is invertible")

print("Determinant of Bminus1:", detBminus1)
if np.isclose(detBminus1, 0):
    print("Matrix Bminus1 is NOT invertible")
else:
    print("Matrix Bminus1 is invertible")
print("Determinant of Bplusi:", detBplusi)
if np.isclose(detBplusi, 0):
    print("Matrix Bplusi is NOT invertible")
else:
    print("Matrix Bplusi is invertible")
print("Determinant of Bminusi:", detBminusi)
if np.isclose(detBminusi, 0):
    print("Matrix Bminusi is NOT invertible")
else:
    print("Matrix Bminusi is invertible")

Determinant of B1: -0.0009165356846477349
Matrix B1 is invertible
Determinant of Bminus1: -0.0009165356846477349
Matrix Bminus1 is invertible
Determinant of Bplusi: -0.006895964315352269
Matrix Bplusi is invertible
Determinant of Bminusi: -0.0068959643153522565
Matrix Bminusi is invertible


- $\theta=N-1$ and $N=4m+1$

In [11]:
import numpy as np

m = 2
N = 4 * m + 1
theta = N-1

# Construct DCT_theta
def DCT_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1 / np.sqrt(N)) * np.cos(((k - theta / 2) * (l - theta / 2)) * 2 * np.pi / N)

# Construct DST_theta
def DST_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1 / np.sqrt(N)) * np.sin(((k - theta / 2) * (l - theta / 2)) * 2 * np.pi / N)

DCT = DCT_theta(N, theta)
DST = DST_theta(N, theta)

P_1 = 0.25 * ((DCT @ DCT) + DCT)
P_minus1 = 0.25 * ((DCT @ DCT) - DCT)
P_plusi = 0.25 * ((DST @ DST) + DST)
P_minusi = 0.25 * ((DST @ DST) - DST)
# Adjusting part1 and part2 to have the same number of rows
part1= P_1[0:m+1,m+1:2*m+1]
part2 = P_1[0:m+1,0][:, np.newaxis]

#-----block selected B(0 ,lambda)--------#----
B1 = np.hstack([part1, part2])
Bminus1 = P_minus1[0:m, m+1:2*m+1]
Bplusi = P_plusi[0:m,m+1:2*m+1]
Bminusi = P_minusi[0:m,m+1:2*m+1]
# Determinants--------------------
detB1 = np.linalg.det(B1)
detBminus1 = np.linalg.det(Bminus1)
detBplusi = np.linalg.det(Bplusi)
detBminusi = np.linalg.det(Bminusi)

# Output results
print("Determinant of B1:", detB1)
if np.isclose(detB1, 0):
    print("Matrix B1 is NOT invertible")
else:
    print("Matrix B1 is invertible")

print("Determinant of Bminus1:", detBminus1)
if np.isclose(detBminus1, 0):
    print("Matrix Bminus1 is NOT invertible")
else:
    print("Matrix Bminus1 is invertible")
print("Determinant of Bplusi:", detBplusi)
if np.isclose(detBplusi, 0):
    print("Matrix Bplusi is NOT invertible")
else:
    print("Matrix Bplusi is invertible")
print("Determinant of Bminusi:", detBminusi)
if np.isclose(detBminusi, 0):
    print("Matrix Bminusi is NOT invertible")
else:
    print("Matrix Bminusi is invertible")

Determinant of B1: -0.0011695280862273083
Matrix B1 is invertible
Determinant of Bminus1: -0.003053420977679921
Matrix Bminus1 is invertible
Determinant of Bplusi: 0.0
Matrix Bplusi is NOT invertible
Determinant of Bminusi: 0.0
Matrix Bminusi is NOT invertible
