<a href="https://colab.research.google.com/github/shirin6767saleh/code-/blob/Fnew/newversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Rationale for Sinusoids Supporting the Spectral Framework of Fractional DFTs
Let $\mathbf{G}_{\theta \in \mathbb{Z}}$ be the family  extends the classical harmonic analysis framework of the DFT by introducing a tunable parameter $\theta$

$\begin{equation}
\mathbf{G}_\theta = \left[ w^{\left(k - \frac{\theta}{2}\right)\left(\ell - \frac{\theta}{2}\right)} \right]_{k,\ell=0}^{N-1},
\end{equation}$
$\theta\in\{0,1,\cdots,2N-1\},w = e^{-j \frac{2\pi}{N}}$

$\begin{align*}
\mathbf{G}_\theta^2 &=
\begin{cases}
\mathbf{J}_{\theta + 1} \oplus  (-1)^\theta \mathbf{J}_{N - \theta - 1}  & \text{for } 0 \leq \theta < N, \\[6pt]
 (-1)^\theta \, \mathbf{J}_{\theta - N+ 1} \oplus \mathbf{J}_{2N - \theta - 1}, & \text{for } N \leq \theta < 2N,
\end{cases}\\
\mathbf{G}_\theta^4 &= I,
\end{align*}$

where:

-  $J$ is the antidiagonal matrix,



In [ ]:
import numpy as np
#parameter
N = 6
theta = 3
# Construct matrix G_theta with normalization 1/sqrt(N)
def G_theta(N, theta):
    w = np.exp(-1j * 2 * np.pi / N)
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1/np.sqrt(N)) * (w ** ((k - theta/2) * (l - theta/2)))

# Construct J_n (matrix with ones on the anti-diagonal)
def J(n):
    J = np.zeros((n, n), dtype=complex)
    for i in range(n):
        J[i, n - 1 - i] = 1
    return J

# Compute G_theta^2 according to the theoretical formula
def G_theta_squared(N, theta):
    if 0 <= theta < N:
        A = J(theta+1)
        B = (-1)**theta * J(N - theta - 1)
    elif N <= theta < 2*N:
        A = (-1)**theta * J(theta - N + 1)
        B = J(2*N - theta - 1)
    else:
        raise ValueError("theta must be between 0 and 2N-1")
    # Block diagonal (direct sum)
    return np.block([
        [A, np.zeros((A.shape[0], B.shape[1]), dtype=complex)],
        [np.zeros((B.shape[0], A.shape[1]), dtype=complex), B]
    ])

if __name__ == "__main__":


    G = G_theta(N, theta)
    G2_direct = G @ G  # matrix multiplication using @
    G2_theory = G_theta_squared(N, theta)

    print("G_theta:")
    print(np.round(G, 3))

    print("\nG_theta^2 (direct multiplication):")
    print(np.round(G2_direct, 3))

    print("\nG_theta^2 (theoretical formula):")
    print(np.round(G2_theory, 3))

    # Test correctness: compare the two results
    error = np.max(np.abs(G2_direct - G2_theory))
    print("\nMax absolute difference between direct and theoretical results:", error)
    if error < 1e-10:
        print("Test PASSED ✅")
    else:
        print("Test FAILED ❌")


G_theta:
[[-0.289-0.289j  0.289-0.289j  0.289+0.289j -0.289+0.289j -0.289-0.289j
   0.289-0.289j]
 [ 0.289-0.289j  0.394-0.106j  0.394+0.106j  0.289+0.289j  0.106+0.394j
  -0.106+0.394j]
 [ 0.289+0.289j  0.394+0.106j  0.394-0.106j  0.289-0.289j  0.106-0.394j
  -0.106-0.394j]
 [-0.289+0.289j  0.289+0.289j  0.289-0.289j -0.289-0.289j -0.289+0.289j
   0.289+0.289j]
 [-0.289-0.289j  0.106+0.394j  0.106-0.394j -0.289+0.289j  0.394-0.106j
  -0.394-0.106j]
 [ 0.289-0.289j -0.106+0.394j -0.106-0.394j  0.289+0.289j -0.394-0.106j
   0.394-0.106j]]

G_theta^2 (direct multiplication):
[[ 0.+0.j -0.-0.j  0.+0.j  1.+0.j  0.-0.j -0.+0.j]
 [-0.-0.j  0.+0.j  1.-0.j  0.-0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.-0.j -0.+0.j -0.-0.j -0.-0.j]
 [ 1.-0.j  0.-0.j -0.+0.j  0.-0.j  0.-0.j  0.+0.j]
 [ 0.-0.j  0.+0.j -0.-0.j  0.-0.j  0.+0.j -1.-0.j]
 [-0.+0.j  0.+0.j -0.-0.j  0.+0.j -1.-0.j -0.+0.j]]

G_theta^2 (theoretical formula):
[[ 0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j  0

#Let the parameterized discrete trigonometric transforms be defined as follows:
$\begin{equation}
\mathrm{DCT}_\theta = \frac{2}{\sqrt{N}}
\left[ \cos\!\left((k - \tfrac{\theta}{2})(l - \tfrac{\theta}{2}) \tfrac{2\pi}{N}\right) \right]_{k,l=0}^{N-1},\quad\mathrm{DST}_\theta = \frac{2}{\sqrt{N}}
\left[ \sin\!\left((k - \tfrac{\theta}{2})(l - \tfrac{\theta}{2}) \tfrac{2\pi}{N}\right) \right]_{k,l=0}^{N-1}.
\end{equation}$

-The sinusoidal transforms $\mathrm{DCT}_\theta$ and $\mathrm{DST}_\theta$ define, respectively, the real and imaginary components of $\mathbf{G}_\theta$, and are mutually orthogonal.

In [2]:
import numpy as np

# Construct DCT_theta
def DCT_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (2/np.sqrt(N)) * np.cos(((k - theta/2) * (l - theta/2)) * 2*np.pi/N)

# Construct DST_theta
def DST_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (2/np.sqrt(N)) * np.sin(((k - theta/2) * (l - theta/2)) * 2*np.pi/N)

# Construct G_theta from DCT and DST
def G_theta_from_DCT_DST(N, theta):
    DCT = DCT_theta(N, theta)
    DST = DST_theta(N, theta)
    return 0.5 * (DCT + 1j * DST)

# Example usage
if __name__ == "__main__":
    N = 6
    theta = 3

    DCT = DCT_theta(N, theta)
    DST = DST_theta(N, theta)
    G = G_theta_from_DCT_DST(N, theta)

    # Check DCT @ DST = 0
    product = DCT @ DST
    max_error_product = np.max(np.abs(product))

    # Check G_theta = 0.5*(DCT + i*DST)
    G_manual = 0.5 * (DCT + 1j * DST)
    max_error_G = np.max(np.abs(G - G_manual))

    print("DCT_theta:")
    print(np.round(DCT, 3))

    print("\nDST_theta:")
    print(np.round(DST, 3))

    print("\nG_theta (from DCT and DST):")
    print(np.round(G, 3))

    print("\nDCT_theta @ DST_theta:")
    print(np.round(product, 10))

    print("\nMax absolute value in DCT_theta @ DST_theta:", max_error_product)
    if max_error_product < 1e-10:
        print("Test PASSED ✅ (DCT_theta @ DST_theta ≈ 0)")
    else:
        print("Test FAILED ❌ (DCT_theta @ DST_theta ≠ 0)")

    print("\nMax absolute difference between G_theta and 0.5*(DCT + i*DST):", max_error_G)
    if max_error_G < 1e-10:
        print("Test PASSED ✅ (G_theta = 0.5*(DCT + i*DST) verified)")
    else:
        print("Test FAILED ❌ (G_theta != 0.5*(DCT + i*DST))")


DCT_theta:
[[-0.577  0.577  0.577 -0.577 -0.577  0.577]
 [ 0.577  0.789  0.789  0.577  0.211 -0.211]
 [ 0.577  0.789  0.789  0.577  0.211 -0.211]
 [-0.577  0.577  0.577 -0.577 -0.577  0.577]
 [-0.577  0.211  0.211 -0.577  0.789 -0.789]
 [ 0.577 -0.211 -0.211  0.577 -0.789  0.789]]

DST_theta:
[[ 0.577  0.577 -0.577 -0.577  0.577  0.577]
 [ 0.577  0.211 -0.211 -0.577 -0.789 -0.789]
 [-0.577 -0.211  0.211  0.577  0.789  0.789]
 [-0.577 -0.577  0.577  0.577 -0.577 -0.577]
 [ 0.577 -0.789  0.789 -0.577  0.211  0.211]
 [ 0.577 -0.789  0.789 -0.577  0.211  0.211]]

G_theta (from DCT and DST):
[[-0.289+0.289j  0.289+0.289j  0.289-0.289j -0.289-0.289j -0.289+0.289j
   0.289+0.289j]
 [ 0.289+0.289j  0.394+0.106j  0.394-0.106j  0.289-0.289j  0.106-0.394j
  -0.106-0.394j]
 [ 0.289-0.289j  0.394-0.106j  0.394+0.106j  0.289+0.289j  0.106+0.394j
  -0.106+0.394j]
 [-0.289-0.289j  0.289-0.289j  0.289+0.289j -0.289+0.289j -0.289-0.289j
   0.289-0.289j]
 [-0.289+0.289j  0.106-0.394j  0.106+0.394j -0.289