<a href="https://colab.research.google.com/github/shirin6767saleh/code-/blob/Fnew/newversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Rationale for Sinusoids Supporting the Spectral Framework of Fractional DFTs
Let $\mathbf{G}_{\theta \in \mathbb{Z}}$ be the family  extends the classical harmonic analysis framework of the DFT by introducing a tunable parameter $\theta$

$\begin{equation}
\mathbf{G}_\theta = \left[ w^{\left(k - \frac{\theta}{2}\right)\left(\ell - \frac{\theta}{2}\right)} \right]_{k,\ell=0}^{N-1},
\end{equation}$
$\theta\in\{0,1,\cdots,2N-1\},w = e^{-j \frac{2\pi}{N}}$

$\begin{align*}
\mathbf{G}_\theta^2 &=
\begin{cases}
\mathbf{J}_{\theta + 1} \oplus  (-1)^\theta \mathbf{J}_{N - \theta - 1}  & \text{for } 0 \leq \theta < N, \\[6pt]
 (-1)^\theta \, \mathbf{J}_{\theta - N+ 1} \oplus \mathbf{J}_{2N - \theta - 1}, & \text{for } N \leq \theta < 2N,
\end{cases}\\
\mathbf{G}_\theta^4 &= I,
\end{align*}$

where:

-  $J$ is the antidiagonal matrix,



In [10]:
import numpy as np
#parameter
N = 6
theta = 3
# Construct matrix G_theta with normalization 1/sqrt(N)
def G_theta(N, theta):
    w = np.exp(-1j * 2 * np.pi / N)
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (1/np.sqrt(N)) * (w ** ((k - theta/2) * (l - theta/2)))

# Construct J_n (matrix with ones on the anti-diagonal)
def J(n):
    J = np.zeros((n, n), dtype=complex)
    for i in range(n):
        J[i, n - 1 - i] = 1
    return J

# Compute G_theta^2 according to the theoretical formula
def G_theta_squared(N, theta):
    if 0 <= theta < N:
        A = J(theta+1)
        B = (-1)**theta * J(N - theta - 1)
    elif N <= theta < 2*N:
        A = (-1)**theta * J(theta - N + 1)
        B = J(2*N - theta - 1)
    else:
        raise ValueError("theta must be between 0 and 2N-1")
    # Block diagonal (direct sum)
    return np.block([
        [A, np.zeros((A.shape[0], B.shape[1]), dtype=complex)],
        [np.zeros((B.shape[0], A.shape[1]), dtype=complex), B]
    ])

if __name__ == "__main__":


    G = G_theta(N, theta)
    G2_direct = G @ G  # matrix multiplication using @
    G2_theory = G_theta_squared(N, theta)

    print("G_theta:")
    print(np.round(G, 3))

    print("\nG_theta^2 (direct multiplication):")
    print(np.round(G2_direct, 3))

    print("\nG_theta^2 (theoretical formula):")
    print(np.round(G2_theory, 3))

    # Test correctness: compare the two results
    error = np.max(np.abs(G2_direct - G2_theory))
    print("\nMax absolute difference between direct and theoretical results:", error)
    if error < 1e-10:
        print("Test PASSED ✅")
    else:
        print("Test FAILED ❌")


G_theta:
[[-0.289-0.289j  0.289-0.289j  0.289+0.289j -0.289+0.289j -0.289-0.289j
   0.289-0.289j]
 [ 0.289-0.289j  0.394-0.106j  0.394+0.106j  0.289+0.289j  0.106+0.394j
  -0.106+0.394j]
 [ 0.289+0.289j  0.394+0.106j  0.394-0.106j  0.289-0.289j  0.106-0.394j
  -0.106-0.394j]
 [-0.289+0.289j  0.289+0.289j  0.289-0.289j -0.289-0.289j -0.289+0.289j
   0.289+0.289j]
 [-0.289-0.289j  0.106+0.394j  0.106-0.394j -0.289+0.289j  0.394-0.106j
  -0.394-0.106j]
 [ 0.289-0.289j -0.106+0.394j -0.106-0.394j  0.289+0.289j -0.394-0.106j
   0.394-0.106j]]

G_theta^2 (direct multiplication):
[[ 0.+0.j -0.-0.j  0.+0.j  1.+0.j  0.-0.j -0.+0.j]
 [-0.-0.j  0.+0.j  1.-0.j  0.-0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.-0.j -0.+0.j -0.-0.j -0.-0.j]
 [ 1.-0.j  0.-0.j -0.+0.j  0.-0.j  0.-0.j  0.+0.j]
 [ 0.-0.j  0.+0.j -0.-0.j  0.-0.j  0.+0.j -1.-0.j]
 [-0.+0.j  0.+0.j -0.-0.j  0.+0.j -1.-0.j -0.+0.j]]

G_theta^2 (theoretical formula):
[[ 0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j  0

#Let the parameterized discrete trigonometric transforms be defined as follows:
$\begin{equation}
\mathrm{DCT}_\theta = \frac{2}{\sqrt{N}}
\left[ \cos\!\left((k - \tfrac{\theta}{2})(l - \tfrac{\theta}{2}) \tfrac{2\pi}{N}\right) \right]_{k,l=0}^{N-1},\quad\mathrm{DST}_\theta = \frac{2}{\sqrt{N}}
\left[ \sin\!\left((k - \tfrac{\theta}{2})(l - \tfrac{\theta}{2}) \tfrac{2\pi}{N}\right) \right]_{k,l=0}^{N-1}.
\end{equation}$

Where

\begin{equation}
\begin{cases}
\mathbf{G}_\theta = \frac{1}{2}\left(\mathrm{DCT}_\theta + i\,\mathrm{DST}_\theta \right), \\[4pt]   
\mathrm{DCT}_\theta \cdot \mathrm{DST}_\theta = \mathbf{0},
\end{cases}
\end{equation}

-Table 2

In [17]:
import numpy as np

# Construct DCT_theta
def DCT_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (2/np.sqrt(N)) * np.cos(((k - theta/2) * (l - theta/2)) * 2*np.pi/N)

# Construct DST_theta
def DST_theta(N, theta):
    k = np.arange(N).reshape(-1, 1)
    l = np.arange(N).reshape(1, -1)
    return (2/np.sqrt(N)) * np.sin(((k - theta/2) * (l - theta/2)) * 2*np.pi/N)

# Construct G_theta from DCT and DST
def G_theta(N, theta):
    DCT = DCT_theta(N, theta)
    DST = DST_theta(N, theta)
    return 0.5 * (DCT + 1j * DST)

# Function to print check result with green tick or red cross
def print_check(name, result):
    symbol = '\u2705' if result else '\u274C'
    print(f"{name} passed? {symbol}")

# Example usage
if __name__ == "__main__":
    N = 6
    theta = 3

    # Compute DCT and DST
    DCT = DCT_theta(N, theta)
    DST = DST_theta(N, theta)

    # 1) Check if DCT @ DST is approximately zero
    check1 = DCT @ DST
    print("DCT @ DST (should be close to zero):")
    print(np.round(check1, 10))
    print_check("Check 1", np.allclose(check1, 0, atol=1e-10))

    # 2) Check G_theta = 0.5*(DCT + i*DST)
    G = G_theta(N, theta)
    G_check = 0.5 * (DCT + 1j * DST)
    print_check("Check 2", np.allclose(G, G_check, atol=1e-10))

    # 3) Check G_theta @ expr_plus - expr_plus ~ 0
    expr_plus = 0.25 * (0.5 * (DCT @ DCT) + DCT)
    check3 = G @ expr_plus - expr_plus
    print_check("Check 3", np.allclose(check3, 0, atol=1e-10))

    # 4) Check G_theta @ expr_minus + expr_minus ~ 0
    expr_minus = 0.25 * (0.5 * (DCT @ DCT) - DCT)
    check4 = G @ expr_minus + expr_minus
    print_check("Check 4", np.allclose(check4, 0, atol=1e-10))

    # 5) Check G_theta @ 0.25*(0.5*(DST@DST)-DST) + i*0.25*(0.5*(DST@DST)-DST) ~ 0
    expr_dst_minus = 0.25 * (0.5 * (DST @ DST) - DST)
    check5 = G @ expr_dst_minus + 1j * expr_dst_minus
    print_check("Check 5", np.allclose(check5, 0, atol=1e-10))

    # 6) Check G_theta @ 0.25*(0.5*(DST@DST)+DST) - i*0.25*(0.5*(DST@DST)+DST) ~ 0
    expr_dst_plus = 0.25 * (0.5 * (DST @ DST) + DST)
    check6 = G @ expr_dst_plus - 1j * expr_dst_plus
    print_check("Check 6", np.allclose(check6, 0, atol=1e-10))


DCT @ DST (should be close to zero):
[[-0.  0. -0.  0. -0. -0.]
 [-0. -0.  0.  0.  0.  0.]
 [-0. -0.  0.  0.  0.  0.]
 [-0.  0. -0.  0. -0. -0.]
 [-0.  0. -0.  0.  0.  0.]
 [ 0. -0.  0. -0. -0. -0.]]
Check 1 passed? ✅
Check 2 passed? ✅
Check 3 passed? ✅
Check 4 passed? ✅
Check 5 passed? ✅
Check 6 passed? ✅
