<a href="https://colab.research.google.com/github/shirin6767saleh/code-/blob/Fnew/oddoddPhi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# $N=2m+1$
-  $0\leq \theta=2p-1<N$

In [1]:
import numpy as np

# Define parameters
m = 3
p = 3
N = 2 * m + 1
theta = 2 * p - 1

# Check if theta is in the valid range [0, N)
if not (0 <= theta < N):
    print(f"Error: theta = {theta} is not in the valid range [0, {N})")
    print("Please choose a different value for p")
    exit()

print(f"Parameters: m = {m}, p = {p}, N = {N}, theta = {theta}")

# Calculate w and G_theta
w = np.exp((-2 * np.pi * 1j) / N)
G_theta = np.zeros((N, N), dtype=complex)
for k in range(N):
    for l in range(N):
        exponent = (k - theta/2) * (l - theta/2)
        G_theta[k, l] = (1/np.sqrt(N)) * (w ** exponent)

# Identity matrix
I = np.eye(N)

# Calculate G_theta squared
G_squared = np.dot(G_theta, G_theta)

# Calculate P_theta and Q_theta
P_theta = 0.5 * (I - G_squared)
Q_theta = 0.5 * (I + G_squared)

# Extract real parts
P_theta_real = np.real(P_theta)
Q_theta_real = np.real(Q_theta)

# Calculate C outside the if block so it's always available
C = np.real(G_theta)

# Construct Phi matrix with safe indexing
components = []

# q_first = Q_theta_real[:p, :] - only if p > 0
if p > 0:
    q_first = Q_theta_real[:p, :]
    components.append(q_first)

# q_last = Q_theta_real[-(m-p):, :] - only if m-p > 0
if m - p > 0:
    q_last = Q_theta_real[-(m-p):, :]
    components.append(q_last)

# p_first = P_theta_real[:p, :] - only if p > 0
if p > 0:
    p_first = P_theta_real[:p, :]
    components.append(p_first)

# p_last = P_theta_real[-(m-p+1):, :] - only if m-p+1 > 0
if m - p + 1 > 0:
    p_last = P_theta_real[-(m-p+1):, :]
    components.append(p_last)

# Combine all rows to form Phi
if components:
    Phi = np.vstack(components)

    # Calculate inverse of Phi
    Phi_inv = np.linalg.inv(Phi)

    # Calculate the transformation: Phi @ C @ Phi_inv
    result = Phi @ C @ Phi_inv

    print("\nResult = Phi @ C @ Phi_inv:")
    print(np.array_str(result, precision=6, suppress_small=True))

    if result.shape[0] >= m+1:
        block = result[0:m+1, 0:m+1]
        print("\nsquare block:")
        print(np.array_str(block @ block, precision=6, suppress_small=True))
    else:
        print(f"\nCannot extract block of size {m+1}x{m+1}")

else:
    print("Error: No rows selected for Phi matrix")

# Print C regardless of whether components is empty or not
print("\nC:")
print(np.array_str(C, precision=6, suppress_small=True))

Parameters: m = 3, p = 3, N = 7, theta = 5

Result = Phi @ C @ Phi_inv:
[[ 0.591009 -0.736976  0.327985 -0.        0.       -0.        0.      ]
 [-0.736976 -0.327985  0.591009  0.        0.       -0.       -0.      ]
 [ 0.327985  0.591009  0.736976 -0.       -0.       -0.        0.      ]
 [-0.        0.        0.        0.       -0.        0.       -0.      ]
 [-0.        0.        0.       -0.       -0.       -0.        0.      ]
 [-0.        0.        0.        0.       -0.       -0.       -0.      ]
 [ 0.       -0.        0.        0.        0.       -0.       -0.      ]]

square block:
[[ 1. -0. -0. -0.]
 [-0.  1.  0.  0.]
 [ 0. -0.  1. -0.]
 [-0.  0.  0.  0.]]

C:
[[ 0.295505 -0.368488  0.163993  0.163993 -0.368488  0.295505  0.      ]
 [-0.368488 -0.163993  0.295505  0.295505 -0.163993 -0.368488 -0.      ]
 [ 0.163993  0.295505  0.368488  0.368488  0.295505  0.163993  0.      ]
 [ 0.163993  0.295505  0.368488  0.368488  0.295505  0.163993  0.      ]
 [-0.368488 -0.163993  0.295

#

1.   $N=2m+1$
2.   $N\leq\theta=2p-1<2N$



In [2]:
import numpy as np

# Define parameters
m = 3
p = 7
N = 2 * m + 1
theta = 2 * p - 1

# Check if theta is in the valid range [N, 2N)
if not (N <= theta < 2*N):
    print(f"Error: theta = {theta} is not in the valid range [{N}, {2*N})")
    print("Please choose a different value for p")
    exit()

print(f"Parameters: m = {m}, p = {p}, N = {N}, theta = {theta}")

# Calculate w and G_theta
w = np.exp((-2 * np.pi * 1j) / N)
G_theta = np.zeros((N, N), dtype=complex)
for k in range(N):
    for l in range(N):
        exponent = (k - theta/2) * (l - theta/2)
        G_theta[k, l] = (1/np.sqrt(N)) * (w ** exponent)

# Identity matrix
I = np.eye(N)

# Calculate G_theta squared
G_squared = np.dot(G_theta, G_theta)

# Calculate P_theta and Q_theta
P_theta = 0.5 * (I - G_squared)
Q_theta = 0.5 * (I + G_squared)

# Extract real parts
P_theta_real = np.real(P_theta)
Q_theta_real = np.real(Q_theta)

# Calculate C
C = np.real(G_theta)

# Construct Phi matrix with safe indexing
components = []

# q_first = Q_theta_real[:p-m-1, :] - only if p-m-1 > 0
if p - m - 1 > 0:
    q_first = Q_theta_real[:p-m-1, :]
    components.append(q_first)

# q_last = Q_theta_real[-(2*m-p+1):, :] - only if 2*m-p+1 > 0
if 2*m - p + 1 > 0:
    q_last = Q_theta_real[-(2*m-p+1):, :]
    components.append(q_last)

# p_first = P_theta_real[:p-m, :] - only if p-m > 0
if p - m > 0:
    p_first = P_theta_real[:p-m, :]
    components.append(p_first)

# p_last = P_theta_real[-(2*m-p+1):, :] - only if 2*m-p+1 > 0
if 2*m - p + 1 > 0:
    p_last = P_theta_real[-(2*m-p+1):, :]
    components.append(p_last)

# Combine all rows to form Phi
if components:
    Phi = np.vstack(components)

    # Calculate inverse of Phi
    Phi_inv = np.linalg.inv(Phi)

    # Calculate the transformation: Phi @ C @ Phi_inv
    result = Phi @ C @ Phi_inv

    print("\nResult = Phi @ C @ Phi_inv:")
    print(np.array_str(result, precision=6, suppress_small=True))

    if result.shape[0] >= m+1:
        block = result[0:m+1, 0:m+1]
        print("\nsquare block:")
        print(np.array_str(block @ block, precision=6, suppress_small=True))
    else:
        print(f"\nCannot extract block of size {m+1}x{m+1}")

else:
    print("Error: No rows selected for Phi matrix")

print("\nC:")
print(np.array_str(C, precision=6, suppress_small=True))



Parameters: m = 3, p = 7, N = 7, theta = 13

Result = Phi @ C @ Phi_inv:
[[ 0.736976  0.591009  0.327985  0.        0.        0.       -0.      ]
 [ 0.591009 -0.327985 -0.736976  0.       -0.       -0.       -0.      ]
 [ 0.327985 -0.736976  0.591009  0.       -0.        0.       -0.      ]
 [-0.        0.       -0.        0.        0.        0.       -0.      ]
 [-0.        0.       -0.        0.        0.       -0.       -0.      ]
 [-0.       -0.       -0.        0.       -0.       -0.        0.      ]
 [-0.       -0.       -0.       -0.       -0.        0.       -0.      ]]

square block:
[[ 1. -0.  0.  0.]
 [ 0.  1.  0. -0.]
 [ 0. -0.  1. -0.]
 [-0. -0. -0.  0.]]

C:
[[ 0.368488  0.295505  0.163993 -0.       -0.163993 -0.295505 -0.368488]
 [ 0.295505 -0.163993 -0.368488 -0.        0.368488  0.163993 -0.295505]
 [ 0.163993 -0.368488  0.295505  0.       -0.295505  0.368488 -0.163993]
 [-0.       -0.        0.       -0.        0.       -0.        0.      ]
 [-0.163993  0.368488 -0.29